---
sudo: false
language: c
matrix:
  include:
    - env: TEST=pre-commit
      services:
        - docker
      script: ./tests/pre-commit.sh

    - env: TEST=terraform
      services:
        - docker
      script: cd tf; ../tests/terraform.sh

    - env: TEST=shellcheck
      services:
        - docker
      script: ./tests/shellcheck.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
